# Cloudflare Pages Configuration

# Build settings
[build]
  command = ""
  publish = "."

# Environment variables (optional)
[build.environment]
  NODE_VERSION = "18"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Redirects
[[redirects]]
  from = "/home"
  to = "/#home"
  status = 301

[[redirects]]
  from = "/about"
  to = "/#about"
  status = 301

[[redirects]]
  from = "/services"
  to = "/#services"
  status = 301

[[redirects]]
  from = "/contact"
  to = "/#contact"
  status = 301
